files:
  - source: /language/master/lang.php
    translation: /language/%locale_with_underscore%/%original_file_name%
  - source: /language/master/lang.php
    translation: /language/%two_letters_code%/%original_file_name%
