name: Translations

on:
  push:
    branches: [ development ]

jobs:
  push-strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload new strings
        uses: crowdin/github-action@1.0.20
        with:
          upload_translations: true
          upload_sources: true
          download_translations: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
